version: '3.9'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000/tcp'
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    environment:
      TARGET_ENV: local
      SERVER_GAME_IP: 0.0.0.0

  postgres:
    image: 'postgres:16'
    container_name: 'lerp-postgres'
    volumes:
      - './local/docker/postgresql:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'lerp-local'

  adminer:
    image: 'adminer:4.7'
    container_name: 'lerp-adminer'
    links:
      - 'postgres:postgres'
    ports:
      - '3010:8080'
    environment:
      ADMINER_DEFAULT_SERVER: 'postgres'
      ADMINER_DESIGN: 'pappu687'